spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://192.168.0.32/spring-cloud-sell?characterEncoding=utf-8&userSSL=false
  rabbitmq:
    host: 192.168.0.32
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.0.32
    port: 6379
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
env:
  dev
merryyou:
  name: 郑龙飞
  url: https://longfeizheng.github.io/
